name: payment_app_flutter
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^4.1.0
  logger: any
  json_annotation: ^4.8.1
  webview_flutter: ^4.8.0
  dio: ^5.4.3+1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  flutter_native_splash: ^2.4.0
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  get_it: ^7.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.3
  image_card: ^0.0.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
  build_runner:
  json_serializable:

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/sp.png
    - assets/logo.png
    - assets/reg.jpg
