// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhJ08l9fDQ92PAwzD7Fh9A68TLJh0qQBQ',
    appId: '1:571893681346:web:0c46d2a0f79d8131363f5b',
    messagingSenderId: '571893681346',
    projectId: 'payment-83a5a',
    authDomain: 'payment-83a5a.firebaseapp.com',
    storageBucket: 'payment-83a5a.appspot.com',
    measurementId: 'G-M0TM4H4VHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_OvlVwPUW96-_y-P511zIKcsWpdTnPBI',
    appId: '1:571893681346:android:797b1e7ccb449c1b363f5b',
    messagingSenderId: '571893681346',
    projectId: 'payment-83a5a',
    storageBucket: 'payment-83a5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhG2GDRNo5KW37yZDDxWuaIDwa55YGWsM',
    appId: '1:571893681346:ios:1800f47161421f4c363f5b',
    messagingSenderId: '571893681346',
    projectId: 'payment-83a5a',
    storageBucket: 'payment-83a5a.appspot.com',
    androidClientId: '571893681346-cdhg5p02rlfm7c9960l6ul6ekj66006u.apps.googleusercontent.com',
    iosClientId: '571893681346-b0anj7b5obbm7opvetd30ptgikst20f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhG2GDRNo5KW37yZDDxWuaIDwa55YGWsM',
    appId: '1:571893681346:ios:1800f47161421f4c363f5b',
    messagingSenderId: '571893681346',
    projectId: 'payment-83a5a',
    storageBucket: 'payment-83a5a.appspot.com',
    androidClientId: '571893681346-cdhg5p02rlfm7c9960l6ul6ekj66006u.apps.googleusercontent.com',
    iosClientId: '571893681346-b0anj7b5obbm7opvetd30ptgikst20f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhJ08l9fDQ92PAwzD7Fh9A68TLJh0qQBQ',
    appId: '1:571893681346:web:df105449ca3b887b363f5b',
    messagingSenderId: '571893681346',
    projectId: 'payment-83a5a',
    authDomain: 'payment-83a5a.firebaseapp.com',
    storageBucket: 'payment-83a5a.appspot.com',
    measurementId: 'G-N8XGBN86GD',
  );

}